apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications-service
  name: notifications-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-service
  template:
    metadata:
      labels:
        app: notifications-service
    spec:
      containers:
      - image: europe-west8-docker.pkg.dev/reservation-system-384520/notifications-service/tcp-production
        name: notifications
        env:
          - name: PORT
            value: '3000'
          - name: GOOGLE_OAUTH_CLIENT_ID
            value: '389172525311-186l9ua03arv2ol26fcihh5km70c57jv.apps.googleusercontent.com'
          - name: GOOGLE_OAUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: google
                key: clientSecret
          - name: GOOGLE_OAUTH_REFRESH_TOKEN
            valueFrom: 
              secretKeyRef:
                name: google
                key: refreshToken
          - name: SMTP_USER
            value: 'anthiboSama@gmail.com'
        ports:
          - containerPort: 3000