apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: notifications-service
  name: notifications-service
spec:
  ports:
  - name: "tcp"
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: notifications-service
  type: ClusterIP 

