apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: payments-service
  name: payments-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-service
  template:
    metadata:
      labels:
        app: payments-service
    spec:
      containers:
      - image: europe-west8-docker.pkg.dev/reservation-system-384520/payments-service/tcp-version
        name: payments
        env:
          - name: PORT
            value: '3001'
          - name: NOTIFICATIONS_HOST
            value: notifications-service 
          - name: NOTIFICATIONS_PORT
            value: '3000'
          - name: STRIPE_SECRET_KEY
            valueFrom:
             secretKeyRef:
              name: stripe
              key: apiKey
        ports:
          - containerPort: 3001
