apiVersion: v1
kind: Service
metadata:
  labels:
    app: payments-service
  name: payments-service
spec:
  ports:
  - name: "tcp"
    port: 3001
    protocol: TCP
    targetPort: 3001
  selector:
    app: payments-service
  type: ClusterIP
